export const COMMON_QUOTE_ASSET = 'USDT';

export const COMMON_BASE_ASSETS = [
  'BTC', 'ETH', 'BNB', 'SOL', 'XRP', 'ADA', 'AVAX', 'DOT', 'TRX', 'LTC',
  'MATIC', 'LINK', 'ATOM', 'NEAR', 'FIL', 'AAVE', 'UNI', 'FTM', 'INJ', 'RNDR',
  'ARB', 'OP', 'SUI', 'LDO', 'DYDX', 'GRT', '1INCH',
  'APE', 'GMT', 'FLOW', 'PEPE', 'FLOKI', 'BONK',
  'DOGE', 'SHIB', 'WIF', 'TURBO', '1000SATS',
  'TON', 'APT', 'SEI'
]; 

// export const SUPPORTED_SYMBOLS = [ // REMOVIDO/COMENTADO
//   'BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'SOL/USDT', 'XRP/USDT', 'ADA/USDT',
//   'AVAX/USDT', 'DOT/USDT', 'TRX/USDT', 'LTC/USDT', 'MATIC/USDT', 'LINK/USDT',
//   'ATOM/USDT', 'NEAR/USDT', 'FIL/USDT', 'AAVE/USDT', 'UNI/USDT', 'FTM/USDT',
//   'INJ/USDT', 'RNDR/USDT', 'ARB/USDT', 'OP/USDT', 'SUI/USDT', 'LDO/USDT',
//   'DYDX/USDT', 'GRT/USDT', '1INCH/USDT', 'APE/USDT', 'GMT/USDT', 'FLOW/USDT',
//   'PEPE/USDT', 'FLOKI/USDT', 'BONK/USDT', 'DOGE/USDT', 'SHIB/USDT', 'WIF/USDT',
//   'TURBO/USDT', '1000SATS/USDT', 'TON/USDT', 'APT/USDT', 'SEI/USDT'
// ]; 